# Generated by Django 6.0.6 on 2026-06-27 14:28

import apps.bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bs_payment_config',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(default=apps.bookings.models.generate_booking_ref, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=20)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utr_number', models.CharField(blank=True, max_length=50)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('ticket_sent', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='coupons.coupon')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trips.trip')),
                ('trip_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='trips.tripdate')),
            ],
            options={
                'db_table': 'bs_bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status', 'created_at'], name='bs_bookings_payment_babde0_idx'), models.Index(fields=['customer_email'], name='bs_bookings_custome_8ad6df_idx')],
            },
        ),
    ]
