# Generated by Django 5.2.3 on 2026-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentConfig',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='utr_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
