# Generated by Django 5.2.3 on 2026-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_delete_paymentconfig_remove_booking_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
