# Generated by Django 5.2.3 on 2026-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_aadhar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
