# Generated by Django 5.2.3 on 2026-07-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_customer_aadhar_booking_customer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTraveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('aadhar', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_travelers', to='bookings.booking')),
            ],
        ),
    ]
