# Generated by Django 5.2.3 on 2026-07-09 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_additionaltraveler'),
        ('trips', '0006_tripdate_bs_trip_dat_is_acti_372389_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trips.tripdate'),
        ),
    ]
