# Generated by Django 5.2.3 on 2026-07-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Creator bio/description'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
