# Generated by Django 5.2.3 on 2026-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_instagram_handle_user_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='bio',
            field=models.TextField(blank=True, help_text='Why do you want to be a creator?'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
