# Generated by Django 5.2.3 on 2026-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kycrequest_bio_kycrequest_instagram_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide from public lists (e.g. Creator leaderboard)'),
        ),
    ]
