# Generated by Django 5.2.3 on 2026-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycrequest',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='kycrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='KYCRequest',
        ),
    ]
