# Generated by Django 5.2.3 on 2026-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_embed_code',
            field=models.TextField(blank=True, help_text='Paste the full YouTube <iframe> embed code here'),
        ),
    ]
