# Generated by Django 6.0.6 on 2026-06-27 14:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bs_destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('destination_text', models.CharField(blank=True, help_text='Fallback text if destination FK not set', max_length=200)),
                ('category', models.CharField(choices=[('group', 'Group Tour'), ('family', 'Family Trip'), ('couple', 'Couple Getaway'), ('solo', 'Solo Adventure'), ('safari', 'Safari'), ('wildlife', 'Wildlife'), ('beach', 'Beach Getaway'), ('mountain', 'Mountain Trek'), ('adventure', 'Adventure'), ('cultural', 'Cultural Tour'), ('spiritual', 'Spiritual Journey')], db_index=True, default='group', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('days', models.PositiveIntegerField(default=1)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_capacity', models.PositiveIntegerField(default=20)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('food_included', models.JSONField(blank=True, default=dict)),
                ('stay_details', models.JSONField(blank=True, default=dict)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('gallery', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.destination')),
            ],
            options={
                'db_table': 'bs_trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override base trip price for this date', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='trips.trip')),
            ],
            options={
                'db_table': 'bs_trip_dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('proposed_dates', models.CharField(blank=True, max_length=100)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('listed', 'Listed as Trip')], db_index=True, default='pending', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='trips.trip')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bs_trip_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_active', 'category'], name='bs_trips_is_acti_5e9ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_featured', 'is_active'], name='bs_trips_is_feat_938415_idx'),
        ),
    ]
