# Generated by Django 5.2.3 on 2026-07-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='agency_name',
            field=models.CharField(default='BOLSTER TRAVEL AGENCY', max_length=100),
        ),
    ]
