# Generated by Django 5.2.3 on 2026-07-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
