# Generated by Django 5.2.3 on 2026-07-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tripdate_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Margin paid to the creator for each booking', max_digits=10),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='margin_requested',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margin requested by the creator', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TripLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bs_trip_likes',
                'unique_together': {('user', 'trip')},
            },
        ),
    ]
