# Generated by Django 5.2.3 on 2026-07-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_creator_margin_triprequest_margin_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='created_trip',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creator_margin',
        ),
        migrations.DeleteModel(
            name='TripLike',
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
    ]
