# Generated by Django 5.2.3 on 2026-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_triprequest_created_trip_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tripdate',
            index=models.Index(fields=['is_active', 'start_date'], name='bs_trip_dat_is_acti_372389_idx'),
        ),
    ]
