# Generated by Django 5.2.3 on 2026-07-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripdate_bs_trip_dat_is_acti_372389_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='agency_name',
            field=models.CharField(default='BOLSTER SAFARI', max_length=100),
        ),
    ]
