# Generated by Django 6.0.6 on 2026-06-27 14:28

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(default=apps.tickets.models.generate_ticket_number, editable=False, max_length=30, unique=True)),
                ('verification_token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('trip_title', models.CharField(max_length=200)),
                ('trip_destination', models.CharField(blank=True, max_length=200)),
                ('trip_dates', models.CharField(blank=True, max_length=100)),
                ('trip_duration', models.CharField(blank=True, max_length=50)),
                ('trip_cover_image', models.URLField(blank=True, max_length=500)),
                ('traveler_name', models.CharField(max_length=150)),
                ('traveler_email', models.EmailField(max_length=254)),
                ('traveler_phone', models.CharField(max_length=20)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itinerary_snapshot', models.JSONField(blank=True, default=list)),
                ('inclusions_snapshot', models.JSONField(blank=True, default=dict)),
                ('meeting_point', models.CharField(blank=True, max_length=300)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_details', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('special_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued to Traveler'), ('distributed', 'Distributed'), ('verified', 'Verified by Agent'), ('used', 'Used / Checked-In'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('issued_to_email', models.EmailField(blank=True, max_length=254)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_location', models.CharField(blank=True, max_length=200)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eticket', to='bookings.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bs_etickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tickets.eticket')),
            ],
            options={
                'db_table': 'bs_ticket_status_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eticket',
            index=models.Index(fields=['status', 'created_at'], name='bs_etickets_status_3a38df_idx'),
        ),
        migrations.AddIndex(
            model_name='eticket',
            index=models.Index(fields=['verification_token'], name='bs_etickets_verific_9f4ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='eticket',
            index=models.Index(fields=['traveler_email'], name='bs_etickets_travele_c9522e_idx'),
        ),
    ]
