# Generated by Django 6.0.6 on 2026-07-01 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Type of forensic event (e.g., login_success, login_failed, unauthorized_access, ticket_verify)', max_length=50)),
                ('username_attempted', models.CharField(blank=True, help_text='The username input, especially useful for tracking brute-force failed login logs', max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict, help_text='JSON payload capturing structural metadata for the audited event (e.g., old vs new values)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forensic Log',
                'verbose_name_plural': 'Forensic Logs',
                'db_table': 'bs_forensic_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
